N=anal_miroblaze_gnu
OBJ_MICROBLAZE=$(N).o

STATIC_OBJ+=${OBJ_MICROBLAZE}
TARGET_MICROBLAZE=$(N).${EXT_SO}

ALL_TARGETS+=${TARGET_MICROBLAZE}

${TARGET_MICROBLAZE}: ${OBJ_MICROBLAZE}
	${CC} $(call libname,$(N)) ${CFLAGS} ${CS_CFLAGS} \
		-o $(TARGET_MICROBLAZE) ${OBJ_MICROBLAZE} ${CS_LDFLAGS}
